const DEFAULT_SIZE = 180;

export const spriteSizesByVersion: any = {
  "red-blue": DEFAULT_SIZE,
  yellow: DEFAULT_SIZE,
  "gold-silver": DEFAULT_SIZE,
  crystal: DEFAULT_SIZE,
  "ruby-sapphire": DEFAULT_SIZE,
  emerald: DEFAULT_SIZE,
  "firered-leafgreen": DEFAULT_SIZE,
  "diamond-pearl": DEFAULT_SIZE,
  platinum: DEFAULT_SIZE,
  "heartgold-soulsilver": 125,
  "black-white": 125,
  colosseum: 125,
  xd: 125,
  "black-2-white-2": 125,
  "x-y": 100,
  "omega-ruby-alpha-sapphire": DEFAULT_SIZE,
  "sun-moon": DEFAULT_SIZE,
  "ultra-sun-ultra-moon": DEFAULT_SIZE,
  "lets-go-pikachu-lets-go-eevee": DEFAULT_SIZE,
  "sword-shield": DEFAULT_SIZE,
  "the-isle-of-armor": DEFAULT_SIZE,
  "the-crown-tundra": DEFAULT_SIZE,
  "brilliant-diamond-and-shining-pearl": DEFAULT_SIZE,
  "legends-arceus": DEFAULT_SIZE,
  "scarlet-violet": DEFAULT_SIZE,
};
